Fix argument parsing in publish-ecr (#4)
Co-authored-by: Matthew Green <matgreen@cisco.com>

diff --git a/publish-ecr b/publish-ecr
--- a/publish-ecr
+++ b/publish-ecr
@@ -20,20 +20,14 @@ show_help() {
     >&2 echo " -p, --platform PLATFORM  XRd platform the image is for"
     >&2 echo "                          (defaults to checking the image name)"
     >&2 echo " -t, --tag TAG            Override the target image tag"
+    >&2 echo "                          (defaults to 'latest')"
     >&2 echo ""
     >&2 echo "This script requires skopeo when publishing an image archive."
     >&2 echo "When publishing from a repository, at least one of skopeo,"
     >&2 echo "docker, or podman must be available."
 }
 
-if [ $# -lt 1 ]; then
-  >&2 echo "Not enough positional arguments specified"
-  show_help
-  exit 1
-fi
-
-SOURCE_IMAGE=$1
-shift
+POSITIONAL_ARGS=()
 
 # Parse the arguments
 while [ $# -gt 0 ]; do
@@ -50,14 +44,25 @@ while [ $# -gt 0 ]; do
       show_help
       exit 255
       ;;
-    * )
+    -* )
       >&2 echo "Unknown option $1"
       show_help
       exit 1
       ;;
+    * )
+      POSITIONAL_ARGS+=("$1")
+      ;;
   esac
   shift
 done
+
+if [ ${#POSITIONAL_ARGS[@]} -ne 1 ]; then
+  >&2 echo "Exactly one positional arg required: SOURCE_IMAGE"
+  show_help
+  exit 1
+fi
+
+SOURCE_IMAGE=${POSITIONAL_ARGS[0]}
 
 if [ -n "${PLATFORM:-}" ]; then
   if [ "$(echo "$PLATFORM" | tr "[:upper:]" "[:lower:]")" = "vrouter" ]; then
